Added grpc tests
IITH-Compilers/ML-Compiler-Bridge pull request #12
Opened 2024-01-26 10:37 UTC by RajivChitale

Added tests for MLCompilerBridge gRPC communication.

2024-01-26 10:43 UTC, svkeerthy requested changes

2024-01-26 10:43 UTC, svkeerthy commented on CMakeLists.txt
> +install(DIRECTORY CompilerInterface DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/MLModelRunner/CompilerInterface)
Please remove ${CMAKE_CURRENT_BINARY_DIR} from here

2024-01-26 10:43 UTC, svkeerthy commented on test/mlbridge-test.py
> +        "../CompilerInterface",
Please use CompilerInterface from the build directory

2024-02-07 08:05 UTC, svkeerthy requested changes

2024-02-07 08:05 UTC, svkeerthy commented on test/include/HelloMLBridge_Env.h
> +//===----------------------------------------------------------------------===//
Please change the header text. This seems to be the  old license.

2024-02-07 08:05 UTC, svkeerthy commented on test/include/ProtosInclude.h
Please add header with license text.

2024-02-17 10:42 UTC, RajivChitale commented on test/include/HelloMLBridge_Env.h
> +//===----------------------------------------------------------------------===//
Changed it to the new license.

2024-02-19 04:52 UTC, svkeerthy approved these changes

2024-02-19 04:52 UTC, merged